theme = "paper"
baseURL = 'https://wushaojun321.github.io/'
languageCode = 'zh-cn'
publishDir = "docs"


[params]
subtitle = 'The Best Widgets on Earth'
color = 'linen'                           # linen, wheat, gray, light
comments = false
rss = true                                # show rss icon
avatar = 'https://avatars.githubusercontent.com/u/22766287'                 # gravatar email or image url
name = '六爸'
bio = 'Stay hungry, stay foolish.'

github = 'wushaojun321'                 # github.com/YOUR_GITHUB_ID

# header social icons
#twitter = 'YOUR_TWITTER_ID'               # twitter.com/YOUR_TWITTER_ID
#instagram = 'YOUR_INSTAGRAM_ID'           # instagram.com/YOUR_INSTAGRAM_ID
#linkedin = 'YOUR_LINKEDIN_ID'             # linkedin.com/in/YOUR_LINKEDIN_ID
#mastodon = 'YOUR_MASTODON_LINK'           # e.g. 'https://mastodon.instance/@xxx'
#threads = '@YOUR_THREADS_ID'              # threads.net/@YOUR_THREADS_ID
#bluesky = 'YOUR_BLUESKY_ID'               # https://bsky.app/profile/YOUR_BLUESKY_ID



# misc
#disableHLJS = true                        # disable highlight.js
#disablePostNavigation = true              # disable post navigation
#monoDarkIcon = true                       # show monochrome dark mode icon
#gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
#math = true                               # enable KaTeX math typesetting globally
#localKatex = false                        # use local KaTeX js/css instead of CDN
#graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)
#favicon = "favicon.ico"                   # customize the default favicon
#appleTouchIcon = "apple-touch-icon.png"   # customize the default Apple touch icon

[menu]

[[menu.main]]
name = "首页"
url = "/"
weight = 1

[[menu.main]]
name = "关于我"
url = "/about/"
weight = 2
