theme = "paper"
baseURL = 'https://wushaojun321.github.io/'
languageCode = 'zh-cn'
publishDir = "docs"

[params]
subtitle = 'The Best Widgets on Earth'
color = 'linen'                           # linen, wheat, gray, light
comments = false
rss = true                                # show rss icon
avatar = 'https://private-1255416588.cos.ap-guangzhou.myqcloud.com/66-avar.jpg'                 # gravatar email or image url
name = '六爸'
bio = 'Stay hungry, stay foolish.'

github = 'wushaojun321'

mermaid = true
[menu]

[[menu.main]]
name = "首页"
url = "/"
weight = 1

[[menu.main]]
name = "关于我"
url = "/about/"
weight = 2
